---
- name: creating user
  hosts: all
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - name: creating user and password
      vars:
        password: "{{ lookup('password', './password.txt-{{ item.name }} length=6')}}"
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        shell: /bin/bash
        comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
        password: "{{ password|password_hash('sha512') }}"
        update_password: on_create
        state: present
      with_items: "{{ users }}"
...
