---
- name: creating user
  hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - user_list.yml
  tasks:
    - name: creating password
      vars:
        password: "{{ lookup('password','./{{item.name}}-password.txt length=6')}}"
      user:          
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        shell: /bin/bash
        comment: "{{ item.first | capitalize }} {{ item.second | capitalize }} {{ item.last | capitalize }}"
        password: "{{ password|password_hash('sha512') }}"
        update_password: on_create
        state: present
      with_items: "{{ users }}"

...
